llvmdev:
  - 20
llvm:
  - 20
mlir:
  - 20
libmlir:
  - 20

# Higher version needed for aarch64
# This is not currently supported on our CI machines
# Await support for this before building for aarch64
# c_stdlib_version: # [linux and aarch64]
#   - 2.34          # [linux and aarch64]
  
cuda_compiler_version:
  - 12.8
  - 13.0